name: ZAP Baseline (nightly)
permissions:
  contents: read
  issues: write
on:
  schedule:
    - cron: "0 6 * * *"   # daily 06:00 UTC
  workflow_dispatch:

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: zaproxy/action-baseline@v0.11.0
        with:
          target: https://kiya.cat
          rules_file_name: .zap-ignore
          cmd_options: >
            -a                  # show alerts in logs
            -m 2                # max 2 mins spider (keeps noise low)
            -d                  # debug logging if you need it; remove if too chatty
