name: Deploy to Cloudflare Pages on merge (disabled)

on:
  # Temporarily disabled while Cloudflare deploys are paused.
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_deploy:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint -- --max-warnings=0

      - name: Build
        run: npm run build
        env:
          VITE_PAGECLIP_API_KEY: ${{ secrets.VITE_PAGECLIP_API_KEY }}
          VITE_TURNSTILE_SITE_KEY: ${{ secrets.VITE_TURNSTILE_SITE_KEY }}
          VITE_TURNSTYLE_SITE: ${{ secrets.VITE_TURNSTYLE_SITE }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: kiyaverse
          branch: main
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
