name: a11y-axe
permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  a11y:
    runs-on: ubuntu-latest
    env:
      PORT: 4174  # Use a different port than other workflows
      PREVIEW_URL: http://localhost:4174
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start preview server
        run: npm run preview -- --port $PORT &
      
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:$PORT

      - name: Run a11y tests
        env:
          PREVIEW_URL: http://localhost:${{ env.PORT }}
        run: npx playwright test tests/a11y.spec.ts

      - name: Upload axe report (if exists)
        uses: actions/upload-artifact@v4
        with:
          name: axe-report
          path: axe-report.json